"""Add nutritional fields to Recipe model

Revision ID: 4515bebd0311
Revises: fix_missing_columns
Create Date: 2025-07-30 13:12:40.022485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4515bebd0311'
down_revision = 'fix_missing_columns'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('planned_meal')
    with op.batch_alter_table('challenge', schema=None) as batch_op:
        batch_op.add_column(sa.Column('difficulty_level', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('criteria', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('max_participants', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_featured', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('created_by', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=200),
               existing_nullable=False)
        batch_op.alter_column('challenge_type',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=50),
               nullable=True)
        batch_op.create_foreign_key(None, 'user', ['created_by'], ['id'])

    with op.batch_alter_table('challenge_participation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('submitted_recipe_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('submission_notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('rank', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_completed', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_winner', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('joined_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('completed_at', sa.DateTime(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'recipe', ['submitted_recipe_id'], ['id'])
        batch_op.drop_column('recipe_id')

    with op.batch_alter_table('meal_plan', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('start_date',
               existing_type=sa.DATETIME(),
               type_=sa.Date(),
               existing_nullable=False)
        batch_op.alter_column('end_date',
               existing_type=sa.DATETIME(),
               type_=sa.Date(),
               existing_nullable=False)

    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('calories', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('protein', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('carbohydrates', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('fat', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('fiber', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('salt', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('sugar', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('sodium', sa.Float(), nullable=True))

    with op.batch_alter_table('shopping_list', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.drop_column('completed_at')
        batch_op.drop_column('generated_from_pantry')
        batch_op.drop_column('meal_plan_id')
        batch_op.drop_column('is_completed')

    with op.batch_alter_table('shopping_list_item', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=200),
               existing_nullable=False)
        batch_op.alter_column('quantity',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.Float(),
               nullable=True)
        batch_op.create_foreign_key(None, 'recipe', ['source_recipe_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shopping_list_item', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('quantity',
               existing_type=sa.Float(),
               type_=sa.VARCHAR(length=64),
               nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)

    with op.batch_alter_table('shopping_list', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_completed', sa.BOOLEAN(), server_default=sa.text('0'), nullable=True))
        batch_op.add_column(sa.Column('meal_plan_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('generated_from_pantry', sa.BOOLEAN(), server_default=sa.text('0'), nullable=True))
        batch_op.add_column(sa.Column('completed_at', sa.DATETIME(), nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)

    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.drop_column('sodium')
        batch_op.drop_column('sugar')
        batch_op.drop_column('salt')
        batch_op.drop_column('fiber')
        batch_op.drop_column('fat')
        batch_op.drop_column('carbohydrates')
        batch_op.drop_column('protein')
        batch_op.drop_column('calories')

    with op.batch_alter_table('meal_plan', schema=None) as batch_op:
        batch_op.alter_column('end_date',
               existing_type=sa.Date(),
               type_=sa.DATETIME(),
               existing_nullable=False)
        batch_op.alter_column('start_date',
               existing_type=sa.Date(),
               type_=sa.DATETIME(),
               existing_nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)

    with op.batch_alter_table('challenge_participation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recipe_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'recipe', ['recipe_id'], ['id'])
        batch_op.drop_column('completed_at')
        batch_op.drop_column('joined_at')
        batch_op.drop_column('is_winner')
        batch_op.drop_column('is_completed')
        batch_op.drop_column('rank')
        batch_op.drop_column('score')
        batch_op.drop_column('submission_notes')
        batch_op.drop_column('submitted_recipe_id')

    with op.batch_alter_table('challenge', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('challenge_type',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=64),
               nullable=False)
        batch_op.alter_column('title',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_by')
        batch_op.drop_column('is_featured')
        batch_op.drop_column('max_participants')
        batch_op.drop_column('criteria')
        batch_op.drop_column('difficulty_level')

    op.create_table('planned_meal',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('meal_plan_id', sa.INTEGER(), nullable=False),
    sa.Column('recipe_id', sa.INTEGER(), nullable=False),
    sa.Column('day_of_week', sa.VARCHAR(length=10), nullable=False),
    sa.Column('meal_type', sa.VARCHAR(length=20), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['meal_plan_id'], ['meal_plan.id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
