"""Add Stripe subscription fields

Revision ID: add_stripe_subscription_fields
Revises: 
Create Date: 2025-08-04 13:30:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_stripe_subscription_fields'
down_revision = '1472c334cea8'  # Reference the merge heads migration
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stripe_subscription_id', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('subscription_status', sa.String(length=32), nullable=True))
        
        # Set default value for existing users
        batch_op.execute("UPDATE user SET subscription_status = 'inactive' WHERE subscription_status IS NULL")
        
        batch_op.create_index(batch_op.f('ix_user_stripe_subscription_id'), ['stripe_subscription_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_stripe_subscription_id'))
        batch_op.drop_column('subscription_status')
        batch_op.drop_column('stripe_subscription_id')
    # ### end Alembic commands ###
